### ISSUE TITLE
Use an input element with CSS

### ISSUE THREAD

**Issue by sbp** [kkuchta/css-only-chat#11]
You can [monitor an input element in CSS](https://github.com/maxchehab/CSS-Keylogging#how-it-works), as [noted by minimax](https://lobste.rs/s/nkf9zm/kkuchta_css_only_chat_truly_monstrous#c_qpwa6z).

**Comment by nylen** [comment]
I was thinking the same, but indeed it won't work with only CSS.  From the [CSS keylogging readme](https://github.com/maxchehab/CSS-Keylogging#haxking-l33t-passw0rds):

>1. Open a website that uses a **controlled component framework** such as React. https://instagram.com.

The "controlled" part is key to the CSS keylogger approach, it means the `value` attribute in the DOM will be updated with each change, not just the `value` property of the element object.

You can make this "work" with a bit of JavaScript as described [here](https://stackoverflow.com/a/10645583/106302) but that's cheating.

Also, dealing with all the possible changes to an input element (non-ASCII characters, emoji, pastes of multiple characters) would be difficult or potentially impossible.
