### ISSUE TITLE
Keyboard layout is unintuitive :(

### ISSUE THREAD

**Issue by ajwood-acquia** [kkuchta/css-only-chat#2]
Can we use a table to force the button layout into a more natural layout? e.g. ergonomic left-handed programmer dvorak

**Comment by hagabaka** [comment]
Why couldn't it just be a form with a text input?

**Comment by yrral86** [comment]
A form could work... We just need a css selector for every possible message they might type...

input[value="a"]
input[value="aa"]
etc.

**Comment by cloudrac3r** [comment]
A text input box would work. But not in the way you're thinking.

First, have a text box with selectors that test for every letter and set the background image. Then, when the server resends the page to update the image URLs, also shift the current text box data into an element and make a new empty input box. So typing the next letter would appear to clear the text box and shift the letter into an element.

I don't see why this wouldn't work.

**Comment by HacKanCuBa** [comment]
Perhaps because nobody coded it yet? Go write some PRs!

**Comment by hagabaka** [comment]
Well, what are your requirements? It says "async web chat using no JS whatsoever on the frontend", and you do have a backend. Is the page not allowed to navigate or submit? Is that what you mean by "async"?

**Comment by Clasen00** [comment]
> Well, what are your requirements? It says "async web chat using no JS whatsoever on the frontend", and you do have a backend. Is the page not allowed to navigate or submit? Is that what you mean by "async"?

Maybe author mean by async that page doesn't reload when it send or get messages

**Comment by ThomasBower** [comment]
Why not use the `[value$=...]` attribute selector to capture the last character in the input box. I'm fairly confident you could use this technique to send requests as the user types in an input text box.

e.g.

If the input value is "h" then `[value$=h]` would match. Then if it's "he", `[value$=e]` would match, and so on. The only difficulty I foresee is multiple of the same letters in a row, but I suspect a similar technique to what is currently used might be able to work.

Additionally, if the input box gets unfocused every time the content gets updated, you could probably stick the `autofocus` attribute onto the input to avoid a clunky UX.

**Comment by David-Mulder** [comment]
@thomasbower As was already explained twice `[]` in CSS are attributes selectors, not property selectors. The attribute is static, the property is dynamic.

**Comment by ThomasBower** [comment]
@David-Mulder Yep, my bad. I tested it soon after. Another idea would be to use different fonts and assign them to different characters as seen [here](https://github.com/jbtronics/CrookedStyleSheets/issues/24).

**Comment by David-Mulder** [comment]
@ThomasBower yeah, that's definitely a smarter idea than mine xD
