### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by rhofour** [kkuchta/css-only-chat#3]
Your lack of a license is preventing me from using this at my company.

Also, you know, my common sense and coworkers.

**Comment by yefim** [comment]
real issue tbh

**Comment by mbrukman** [comment]
FWIW, per [GitHub docs on licensing](https://help.github.com/articles/licensing-a-repository/#choosing-the-right-license):

> [...] without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license.

so this is preventing folks from using, distributing, or extending this software in any way. Please consider choosing an open-source license to make it possible to do this.

**Comment by Mis012** [comment]
it's not "per github docs", they just inform you on the common legislation

**Comment by rithvikvibhu** [comment]
Please, please pick one from https://choosealicense.com/ so that we can start using this.

I'm also thinking of porting this to NodeJs to easily integrate with existing servers.

**Comment by kkuchta** [comment]
Man, I'm really hard-pressed to think of any truly legit use for this except as a cautionary example.  I added the MIT license, but *please* let me know what you end up using it for XD.
