### ISSUE TITLE
How would I run this on my own computer?

### ISSUE THREAD

**Issue by 12944qwerty** [kkuchta/css-only-chat#4]
Forgive me if I am being stupid. (I probably am here)

**Comment by Gabgab2003** [comment]
1. Install ruby
2. Install redis and stuff if it's not installed
3. Run the server
4. Connect to the server via browser
I'm too lazy for more detailed stuff

**Comment by akky** [comment]
I wrote Docker files. If you use Docker, #7 might help.

**Comment by 12944qwerty** [comment]
@kkuchta I've never used ruby. So I doubt I have it installed, (or at a decent version). How would I run this otherwise?

**Comment by 12944qwerty** [comment]
I don't know Docker or ruby. So what do I do? (how do I install ruby properly?)

**Comment by 12944qwerty** [comment]
I am confused, when did Gabgab say anything?

**Comment by kkuchta** [comment]
That really depends on your OS and individual circumstances - I'm not sure I can help you there.  I'd check out https://www.ruby-lang.org/en/downloads/ as a starting point?

**Comment by MoonBall** [comment]
@12944qwerty 
1. install [rvm](http://rvm.io/), which is like nvm. `\curl -sSL https://get.rvm.io | bash -s stable`
2. install bundle, `sudo gem install bundler`

**Comment by logicalpermission7** [comment]
so once you have the server up... in your browser type localhost:9292

**Comment by kkuchta** [comment]
See also https://github.com/kkuchta/css-only-chat/blob/master/INSTALL.md
