### ISSUE TITLE
Y u no mention Ruby?

### ISSUE THREAD

**Issue by Rudoslav** [kkuchta/css-only-chat#6]
Ruby called yesterday. 
She wants you to put her into the title.

**Comment by kkuchta** [comment]
Ruby, my friend, needs no introduction.  🌹

**Comment by kkuchta** [comment]
;)

For real, though, the idea is that only css (and html) is used in the frontend, where traditionally you'd expect JS to be in the mix.  It lets it "work" (insofar as it works at all) in browsers with JS disabled.  The requirement of a backend isn't as relevant to the overall idea so I didn't mention it.  ¯\_(ツ)_/¯
